/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./src/components/AccountCard.vue')['default']
    AccountSidebar: typeof import('./src/components/AccountSidebar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CallToAction: typeof import('./src/components/CallToAction.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    FeatureGrid: typeof import('./src/components/FeatureGrid.vue')['default']
    GoogleAISetupWizard: typeof import('./src/components/GoogleAISetupWizard.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    HelpTooltip: typeof import('./src/components/HelpTooltip.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    IntegrationCard: typeof import('./src/components/onboarding/IntegrationCard.vue')['default']
    IntegrationItem: typeof import('./src/components/IntegrationItem.vue')['default']
    IntegrationsGrid: typeof import('./src/components/IntegrationsGrid.vue')['default']
    OAuthSetupWizard: typeof import('./src/components/OAuthSetupWizard.vue')['default']
    OAuthSetupWizardEnhanced: typeof import('./src/components/OAuthSetupWizardEnhanced.vue')['default']
    OnboardingChecklist: typeof import('./src/components/OnboardingChecklist.vue')['default']
    PrimaryButton: typeof import('./src/components/onboarding/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/onboarding/SecondaryButton.vue')['default']
    StepProgressBar: typeof import('./src/components/onboarding/StepProgressBar.vue')['default']
    StepsSection: typeof import('./src/components/StepsSection.vue')['default']
    TierDetailsModal: typeof import('./src/components/TierDetailsModal.vue')['default']
    TutorialOverlay: typeof import('./src/components/TutorialOverlay.vue')['default']
  }
}
